import os
import json
import boto3
from datetime import datetime, timedelta

# AWS Clients
ce = boto3.client('ce')
sns = boto3.client('sns')

# Environment Variables
SNS_TOPIC_ARN = os.environ.get("SNS_TOPIC_ARN")
THRESHOLD_USD = float(os.environ.get("THRESHOLD_USD", "50"))  # Default = $50
TIME_PERIOD = os.environ.get("TIME_PERIOD", "DAILY")  # DAILY or MONTH_TO_DATE
GRANULARITY = "DAILY"  # Always daily for alerts
TEST_MODE = True  # Set True to always send a test email, False for real alerts

def get_time_range():
    """
    Returns start & end dates for Cost Explorer query.
    CE requires END date to be exclusive.
    """
    today = datetime.utcnow().date()

    if TIME_PERIOD.upper() == "MONTH_TO_DATE":
        start = today.replace(day=1)
        end = today
    else:
        # DAILY → check yesterday by default
        yesterday = today - timedelta(days=1)
        start = yesterday
        end = yesterday

    # Cost Explorer END date must be +1 day (exclusive)
    return start.isoformat(), (end + timedelta(days=1)).isoformat()


def get_cost(start, end):
    """
    Calls AWS Cost Explorer and returns the total unblended cost.
    """
    try:
        response = ce.get_cost_and_usage(
            TimePeriod={"Start": start, "End": end},
            Granularity=GRANULARITY,
            Metrics=["UnblendedCost"]
        )

        total = 0.0
        for entry in response.get("ResultsByTime", []):
            amt = entry.get("Total", {}).get("UnblendedCost", {}).get("Amount", "0")
            total += float(amt)

        print(f"[INFO] Retrieved AWS cost: ${total:.4f} for period {start} to {end}")
        return total

    except Exception as e:
        print("[ERROR] Failed to fetch cost:", str(e))
        return 0.0


def send_alert(cost, start, end):
    """
    Sends an SNS email notification.
    """
    subject = f"⚠ AWS Cost Alert — ${cost:.2f} spent"
    message = (
        f"Your AWS cost from {start} to {end} is **${cost:.2f}**, "
        f"which is above your threshold of **${THRESHOLD_USD:.2f}**.\n\n"
        "Recommended actions:\n"
        "- Check Cost Explorer for high-cost services\n"
        "- Delete unused EC2, EBS, RDS, Snapshots\n"
        "- Review free-tier eligible resources\n\n"
        "Alert generated by: Cloud Cost Optimizer Bot 🚀"
    )

    try:
        sns.publish(
            TopicArn=SNS_TOPIC_ARN,
            Subject=subject,
            Message=message
        )
        print("[INFO] SNS alert sent successfully")

    except Exception as e:
        print("[ERROR] SNS publish failed:", str(e))


def lambda_handler(event, context):
    """
    Main Lambda handler.
    """
    print("[INFO] Executing Cloud Cost Optimizer Bot...")

    start, end = get_time_range()
    cost = get_cost(start, end)

    # ✅ Force sending email if TEST_MODE = True, otherwise check threshold
    if TEST_MODE or cost >= THRESHOLD_USD:
        print(f"[ALERT] Sending SNS alert (cost=${cost:.2f}, threshold=${THRESHOLD_USD:.2f})")
        send_alert(cost, start, end)
        return {'status': 'ALERT_SENT', 'cost': cost}

    print(f"[OK] Cost ${cost:.2f} is below threshold ${THRESHOLD_USD:.2f}")
    return {'status': 'OK', 'cost': cost}
